site_name: Stretch RE1
repo_url: https://github.com/hello-robot/stretch_docs
site_description: "Hello Robot User Documentation"
use_directory_urls: True
nav:
 - Home: README.md
 - Forum: "https://forum.hello-robot.com/"
theme:
 name: flatly
 logo: images/hello_robot_logo.png
extra_css: [extra.css]
